nanoporeReport:
  project_root: /home/ubuntu/projects/nanoporeReport/
  output_root: results
  input_root: input
  build: hg38  #hg38
  annovar_script: /home/ubuntu/projects/nanoporeReport/workflow/annovar/table_annovar.pl
  human_db: /home/ubuntu/projects/nanoporeReport/workflow/annovar/humandb/
  dp_threshold: 500

jasperserver:
  hostname: localhost
  port: 8080
  username: jasperadmin
  password: jasperadmin
  report_path: reports/reports/bigNanopore.pdf

flaskAPI:
  hostname: localhost
  port: 5000
  allowFrom: 0.0.0.0
  sub_command: /home/ubuntu/projects/nanoporeReport/workflow/snakemake/snake.sh
  log_dir: /home/ubuntu/projects/nanoporeReport/api/logs

database:
  hostname: localhost
  port: 5432
  db: nanopore
  username: postgres
  password: postgres
  all_pass_table: report.historical_pass
  target_table: report.targets
  vcf_table: report.vcf_pass
  unique_vcf_rows: report.unique_vcf_rows
